### ISSUE TITLE
Handle data being sent failiure

### ISSUE THREAD

**Issue by MrE-fpv** [eedok/VelocidroneWebSocketConsumer#6]
If the proxy can't send the data, buffer it and retry.

**Comment by MrE-fpv** [comment]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at async postMessage (file:///F:/Dev/VelocidroneWebSocketConsumer/proxy.js:125:13)
    at async WebSocket.message (file:///F:/Dev/VelocidroneWebSocketConsumer/proxy.js:42:3) {
  cause: SocketError: other side closed
      at TLSSocket.onSocketEnd (node:internal/deps/undici/undici:8280:26)
      at TLSSocket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
socket: {
      localAddress: '192.168.0.10',
      localPort: 53123,
      remoteAddress: '0.0.0.0',
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 3297,
      bytesRead: 1701
    }
  }
}

Error: Failed to post message to https://velocevent.com/racestatus: 401 Unauthorized
    at postMessage (file:///F:/Dev/VelocidroneWebSocketConsumer/proxy.js:128:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.message (file:///F:/Dev/VelocidroneWebSocketConsumer/proxy.js:42:3)
